version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/belavaishalichuphal/leaderboard/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD

jobs:
  hello-job:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: echo "Wow you did it!!"
  test-job:
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # echo Another job creation Done!

workflows:
  my-workflow:
    jobs:
      - hello-job
  my-custom-workflow:
    jobs:
      - test-job
